#!/bin/bash

# This script makes the world nice-looking for the world.

cd man
rm *sgml
cd ..

for item in `ls *.c`
do
  ~mikal/opensource-stable/autodocbook/autodocbook $item
done

cd man
for item in `ls *sgml`
do
  docbook2man $item > `echo $item | sed 's/sgml/man/'`
done
cd ..

automake
autoconf
./configure
make clean

# Get rid of core files
for item in `find . | grep core`
do
  rm -i $item
done

delname="Makefile autom4te.cache config.cache config.log config.status logfile math config.h output.pdf .deps"

# Get rid of makefiles
for filename in $delname
do
  for item in `find . -name $filename -print`
  do
    rm -ri $item
  done
done

# How much space do we use?
du -sk


