#!/bin/bash -e

# This script makes the world nice-looking for the world.

cd man
rm *sgml || true
cd ..

for item in `ls *.c`
do
  /data/src/stillhq_public/trunk/autodocbook/autodocbook $item
done

cd man
for item in `ls *sgml`
do
  docbook2man $item
done
cd ..

automake
autoconf
./configure
make clean

# Get rid of core files
for item in `find . | grep core`
do
  rm -i $item
done

# Get rid of unwanted files
for filename in Makefile autom4te.cache config.cache config.log config.status logfile math config.h output.pdf .deps
do
  for item in `find . -name $filename -print`
  do
    rm -rf $item || true
  done
done

rm -ri "#*#" || true
rm -ri *~ || true

# How much space do we use?
du -sk


